### ISSUE TITLE
Improving comment colors in XML

### ISSUE THREAD

**Issue by robertmathew** [LouisCAD/GoogleDevelopersColorScheme#5]
Hey,
Currently, for line comment color in Java code is #ec4c7a. But for XML, comment color is #000000. 
![screenshot from 2016-02-20 10-23-28](https://cloud.githubusercontent.com/assets/2344947/13194571/5c36bfb4-d7bc-11e5-9a77-f43e63e39f36.png)

Suggestion: If we change XML comment color to #ec4c7a, it will look better than before.
![screenshot from 2016-02-20 10-23-56](https://cloud.githubusercontent.com/assets/2344947/13194573/675c1f42-d7bc-11e5-921f-282b0e78e777.png)

**Comment by LouisCAD** [comment]
Hi!
I have a personal preference for black comments in xml, because it's more easily noticeable, and IIRC, xml displays all non comments lines in a non black and non dark gray color. In java, the comments are red because most of the code is in dark gray, and red is more noticeable in this context.

If you are not the only one wanting xml comments in red, please, add a +1 comment here so I publish a version with red xml comments. Anyway, you can already edit the color for your version right now :wink:

**Comment by robertmathew** [comment]
Okay. There is no need to update the color scheme. I will change the colors for my prefernces.😊 

Bravo on the color scheme. I liked it a lot. 😍

**Comment by LouisCAD** [comment]
Glad my color scheme is useful and appreciated :) I like it a lot too 😉
Merci ☺
